# Generated by Django 4.1.4 on 2023-03-24 21:38

import crm.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', crm.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
